- id: helm-schema
  args: []
  description: Helm plugin for generating values.schema.json from single or multiple values files. Works only with Helm3 charts.
  entry: scripts/git-hook.sh
  language: script
  name: Helm values schema json
  pass_filenames: false
  require_serial: true
