# Required
input:
  - '.schema.yaml'

draft: 2020 # @schema enum: [4, 6, 7, 2019, 2020]; default: 2020
indent: 4 # @schema default: 4
output: values.schema.json # @schema default: values.schema.json

bundle: true # @schema default: false
bundleRoot: testdata # @schema default: ""
bundleWithoutID: true # @schema default: false

schemaRoot:
  id: https://example.com/schema
  ref: bundle/simple-subschema.schema.json
  title: Helm Values Schema
  description: Schema for Helm values
  additionalProperties: true
