# Required
input:
  - ".schema.yaml"

draft: 2020 # @schema enum: [4, 6, 7, 2019, 2020]; default: 2020
indent: 4 # @schema default: 4
output: values.schema.json # @schema default: values.schema.json

bundle: true # @schema default: false
bundleRoot: "" # @schema default: ""
bundleWithoutID: true # @schema default: false

k8sSchemaURL: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/{{ .K8sSchemaVersion }}/
k8sSchemaVersion: "v1.33.1"

useHelmDocs: true # @schema default: false

schemaRoot:
  id: https://example.com/schema
  ref: testdata/bundle/simple-subschema.schema.json
  title: Helm Values Schema
  description: Schema for Helm values
  additionalProperties: true
