name: "schema"
version: "1.9.2"
usage: "generate values.schema.json from values yaml"
description: "Helm plugin for generating values.schema.json from multiple values files."
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/schema"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; HELM_PLUGIN_UPDATE=1 ./scripts/install.sh"
